### ISSUE TITLE
btrees memleak on C_Finalize

### ISSUE THREAD

**Issue by p-steuer** [opencryptoki/opencryptoki#166]
opencryptoki stores state information in five btrees: sess_btree, sess_obj_btree, priv_token_obj_btree, publ_token_obj_btree and object_map_btree.

When a stdll is unloaded by C_Finalize, only  priv_token_obj_btree and publ_token_obj_btree seem to be deallocated and pointers to the memory allocated for the remaining btrees are lost. To be investigated.

**Comment by ifranzki** [comment]
sess_obj_btree is freed when the session terminates, which should happen during or before C_Finalize. C_Finalize calls session_mgr_close_all_sessions() which then closes all left over sessions and also frees its session objects from sess_obj_btree.

This should also cleanup  sess_btree, since when all sessions are closed, the sess_btree is empty, thus no need to further cleanup sess_btree.

Similar with object_map_btree. When all objects are freed (token objs via object_mgr_purge_token_objects(), as well as session objs via session_mgr_close_all_sessions()) then this tree is empty, thus no need to further cleanup.

**Comment by p-steuer** [comment]
As far as i investigated the problem it is supposed to work exactly as you said. However, valgrind still reports memory loss in case of said three btrees.

**Comment by p-steuer** [comment]
Problem with the freeing procedures in session_mgr_close_all_sessions, object_mgr_purge_token_objects etc was that nodes on the free list(*) were ignored.

(*) Free listed nodes are currently not used but were not deallocated such that the can be reused later to save alloc/free calls. Question is if the number of such nodes should be restricted to prevent an excessive amount of them.
