### ISSUE TITLE
--disable-locks fails to build

### ISSUE THREAD

**Issue by xnox** [opencryptoki/opencryptoki#287]
New opencryptoki is not available on any architecture in ubuntu because it fails to build from source on armhf:

https://github.com/opencryptoki/opencryptoki/commit/1f56f54a53b331f20bde3b2f23bc089327e9b6ca

broke armhf build:

```
$ ./configure --build=arm-linux-gnueabihf --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/arm-linux-gnueabihf --libexecdir=${prefix}/lib/arm-linux-gnueabihf --disable-maintainer-mode --disable-dependency-tracking --enable-tpmtok --with-systemd=/lib/systemd/system ac_cv_path_CHGRP=true --disable-locks
...
fails with
...
checking csulincl.h presence... no
checking for csulincl.h... no
configure: error: in order to build opencryptoki with transactional memory,
libitm and gcc>=4.7 is required
	tail -v -n \+0 config.log
```

**Comment by p-steuer** [comment]
We may need more information on your build environmet here. The exact same configure line works for me on ubuntu 20.04, and also on my other systems and the right code is build (transactional memory instead of locks). I only ever saw this message when libitm devel was not present on the system in which case its justified.

**Comment by xnox** [comment]
or maybe i am confused.

do we want enabling locks everywhere, and enabling locks is impossible on

**Comment by xnox** [comment]
> We may need more information on your build environmet here. The exact same configure line works for me on ubuntu 20.04, and also on my other systems and the right code is build (transactional memory instead of locks). I only ever saw this message when libitm devel was not present on the system in which case its justified.

libitm does not exist on armhf only, out of the 7 architectures that ubuntu now supports

**Comment by p-steuer** [comment]
> libitm does not exist on armhf only, out of the 7 architectures that ubuntu now supports

So you cant build with transactional memory on armhf since the transactional memory implementation that opencryptoki uses is libitm.

> do we want enabling locks everywhere?

Some years ago, some (not all) locking in opencryptoki was replaced by transactional memory to improve multi threaded performance. While it really helped MT performance, but mostly because the locking implementation was very naive. On the other hand, we regularly saw difficult to debug problems with the TM build in the last years. So we decided to make the more stable locking build the default and left TM build as a feature. Theres a hughe PR https://github.com/opencryptoki/opencryptoki/pull/283 which completely reworks all of opencryptokis locking and hopefully makes it more stable and performant. We plan to include it in the next release (mid of may).

**Comment by xnox** [comment]
Ok, so i think i have everything correct in my mind now:

```
$ git checkout 7fca455a9
<patch configure.ac to print status of $enable_locks variable>
$ ./configure | grep locks
  Build with locks:   no
$ ./configure --enable-locks | grep locks
  Build with locks:   yes
$ ./configure --disable-locks | grep locks
  Build with locks:   yes
$ ./configure --enable-locks=no | grep locks
  Build with locks:   yes
```

Meaning old configure script was buggy, and we were building with transactional memory on all architectures, but armhf. On armhf we passed `--disable-locks` which actually, was doing `--enable-locks` as needed there.

Patching the current master to show enable-locks, shows that it is operating correctly:

```
$ git checkout master
<patch to show locks status>
$ autoreconf -fi
$ ./configure | grep locks
	Build with locks:	yes
$ ./configure --enable-locks | grep locks
	Build with locks:	yes
$ ./configure --enable-locks=no | grep locks
	Build with locks:	no
$ ./configure --disable-locks | grep locks
	Build with locks:	no
```

So v3.13 and up is good, and consistent w.r.t. locks configure option. And prior releases were buggy.

I will now switch ubuntu to use locks (the new default) on all architectures.
