### ISSUE TITLE
Examine NODH define

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#30]
The NODH define is included in each token's tok_struct.h but most do not have the function in
their token specific file nor in their mech_list. Needs cleaning up.

Migrated from https://sourceforge.net/p/opencryptoki/bugs/111/

**Comment by ifranzki** [comment]
I checked the tokens, and it seems that the oly tokens that support DH are the soft token and the EP11 token. The EP11 token does not use common code/functions in tok_struct.h. The soft token implements the DF functions using OpenSSL. 

The CCA token has NODH in its makefile, but also implements the 2 token specific DH functions, but they simply return CKR_FUNCTION_NOT_SUPPORTED. Also due to NODA in the makefile the tokstruct uses NULL for the 2 functions. And the mechlist does not contain the DH mechanisms.

The ICA and TPM tokens have NODH in its makefile, but also implements the 2 token specific DH functions, but those functions do not even compile (when NODH is removed). Also the mechlists do not contain the DH mechanisms.

I would suggest to remove the incomplete implementation of the 2 token specific DH functions for CCA, ICA and TPM tokens, and specify NULL in the tokstruct unconditionally.  That way only the soft token keeps its working implementation, as well as the EP11 token. Would save us some dead code in the other tokens.

Opinions?

**Comment by p-steuer** [comment]
Fixed by #151 . Closed.
