### ISSUE TITLE
All the algorithm context structures could be aggregated

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#42]
There are several algorithm or mechanism contexts, i.e. ENCR_DECR_CONTEXT, SIGN_VERIFY_CONTEXT, DIGEST_CONTEXT. It seems these could be possibly integrated into only one. 
The code should be examined and see if this is feasible.

Migrated from https://sourceforge.net/p/opencryptoki/bugs/133/

**Comment by ifranzki** [comment]
Although it is not stated explicitly in the PKCS#11 standard, but in a session multiple operations may be active at a time. I.e. there can be a digest operation being active and at the same time a sign operation. This is used by the so called dual-function cryptographic functions like `C_DigestEncryptUpdate` and friends. This require that the application initialize a digest operation as well as an encrypt operation in the same session.

However, there can only be one operations of the same type be active at a time, i.e. there can not be two sign operations active in one session.

So although the algorithm context structures of openCryptoki look similar and could technically be aggregated into one single structure definition, we still need to have separate instances of the context for each operation type, in order to support multiple operations being active at the same time.

From a type-safety point of view I find it beneficial when the different context structures of the different operation types are different structure types, as well. This allows the compiler to check if one is passing the right context structure to operation specific function.

I a closing this issue for now, since I don't see that tis will be changed in the foreseeable future.
