### ISSUE TITLE
Missing error handlings of pthread_mutex_lock

### ISSUE THREAD

**Issue by ryancaicse** [opencryptoki/opencryptoki#502]
Hi, there are two inconsistent places where the return values of pthread_mutex_lock are not handled. **The rest of them are well-handled.**
https://github.com/opencryptoki/opencryptoki/blob/b0e62ec7f2d7dc9c6a4ccb600d998990acab0e93/usr/lib/common/trace.c#L293-L296

https://github.com/opencryptoki/opencryptoki/blob/8e9800b492f7a40ed5dfcd85e042701b6a5c5a26/usr/lib/ica_s390_stdll/ica_specific.c#L277-L283

**Comment by ifranzki** [comment]
Thanks for reporting those missing error checking issues.

The first one in trace.c is not critical, its just used when tracing is enabled, and would only cause corrupted trace messages if the lock fails. I guess its better to anyway try to write the trace message, even if the lock failed, instead of not writing the trace message.  There is really not much that can be done here if the lock fails. 

The second one needs error checking to avoid concurrent calls to ica_random_number_generate.
