### ISSUE TITLE
Various missing includes

### ISSUE THREAD

**Issue by NHOrus** [opencryptoki/opencryptoki#770]
It causes build to fail with GCC-14 or with `-Werror=implicit-function-declaration` set

https://github.com/opencryptoki/opencryptoki/blob/08cc1eb18d51e73fabba7103e24d8e215b132ee4/usr/include/local_types.h#L50
but pthread.h is not included or referenced in other includes

https://github.com/opencryptoki/opencryptoki/blob/08cc1eb18d51e73fabba7103e24d8e215b132ee4/usr/sbin/pkcsslotd/mutex.c#L30
https://github.com/opencryptoki/opencryptoki/blob/08cc1eb18d51e73fabba7103e24d8e215b132ee4/usr/lib/common/trace.c#L198
https://github.com/opencryptoki/opencryptoki/blob/08cc1eb18d51e73fabba7103e24d8e215b132ee4/usr/lib/hsm_mk_change/hsm_mk_change.c#L64
https://github.com/opencryptoki/opencryptoki/blob/08cc1eb18d51e73fabba7103e24d8e215b132ee4/usr/lib/common/utility.c#L113
but fcntl.h is not included or referenced in other includes

There may be others, but I was unable to find them due to them being masked behind existing errors.

**Comment by NHOrus** [comment]
On that note:
Could there be a minor version release with #741 #770 and #769, that is known to build correctly with GCC-14 and so Gentoo can go without patching it everywhere? We still have 3.6.1 in portage and I want new version to be as close to upstream as possible.
Thank you.

**Comment by ifranzki** [comment]
Sorry, but it DOES build error/warning free on all major distros, so I guess it must be a problem in your setup.

**Comment by ifranzki** [comment]
`opencryptoki/usr/sbin/pkcsslotd/mutex.c` includes `slotmgr.h` which inclides `pthread.h`.

`opencryptoki/usr/lib/common/trace.c` does include `pthread.h` directly.

`opencryptoki/usr/lib/hsm_mk_change/hsm_mk_change.c` does not need `pthread` at all....

opencryptoki/usr/lib/common/utility.c does include `pthread.h` directly.

The only valid thing is maybe that `opencryptoki/usr/include/local_types.h` should prpbaly include `pthread.h` directly, since it uses `pthread_mutex_t`. 

Still it compiles error/warning free (even with `-Wall`) as far as I can tell.

**Comment by ifranzki** [comment]
> Could there be a minor version release with https://github.com/opencryptoki/opencryptoki/pull/741 https://github.com/opencryptoki/opencryptoki/issues/770 and https://github.com/opencryptoki/opencryptoki/issues/769, ....

https://github.com/opencryptoki/opencryptoki/pull/741  is already included in 3.23.0.

**Comment by NHOrus** [comment]
It builds with clang-glibc. Sorry for being hastly with going upstream and wasting time.
