### ISSUE TITLE
 Investigate settings for private and secret keys

### ISSUE THREAD

**Issue by dodys** [opencryptoki/opencryptoki#8]
For secret and private keys, in object_create(), we first call object_create_skel() which checks, validates and adds default attributes.
In the priv|secret_key_set_default_attributes() we add and set LOCAL, SENSITIVE, ALWAYS_SENSITIVE, EXTRACTABLE, NEVER_EXTRACTABLE
attributes to defaults.
However, later in object_create, after object_create_skel, for private and secret keys, we check for SENSITIVE and EXTRACTABLE and then
get their values. We then call build_attribute() to create ALWAYS_SENSITIVE and NEVER_EXTRACTABLE attributes and set their values to their couterpart's values.

build_attribute appears to create another attribute into template rather than change the value for an existing attribute.
Thus, it appears we are adding the NEVER_EXTRACTABLE and ALWAYS_SENSITIVE attributes twice to the template and each occurence could have a different value.

Investigate and see if this is true.

This issue was migrated from: https://sourceforge.net/p/opencryptoki/bugs/138/

**Comment by ifranzki** [comment]
Well, the code currently uses template_update_attribute() to update NEVER_EXTRACTABLE and ALWAYS_SENSITIVE attributes, so the attributes will definitely not be there twice. 

However, I wonder why the NEVER_EXTRACTABLE and ALWAYS_SENSITIVE attributes are set here again since they are already set to FALSE inside priv_key_set_default_attributes() and secret_key_set_default_attributes() which is called from object_create_skel() via template_add_default_attributes(). setting them again to FALSE does not make sense to me....

Also the template_attribute_find() for CKA_SENSITIVE and CKA_EXTRACTABLE are superfluous since both are also set in priv_key_set_default_attributes() and secret_key_set_default_attributes(). So the exist iin any case, and the code does not use its value anyway in the code part in question. 

So I would say the  whole block for` if (class == CKO_PRIVATE_KEY || class == CKO_SECRET_KEY) {` can be removed. Unless I am overseeing something, this code does not do anything useful.

**Comment by p-steuer** [comment]
3c50c66 fixed private and secret keys generated by C_CreateObject having CKA_NEVER_EXTRACTABLE=TRUE, violating pkcs11 (see commit message).

But your right, essential the whole if block can be removd, because the defaults are already correct: Tested it and pushed 6f78446.

**Comment by p-steuer** [comment]
Fixed by PR #142. Closing.
